import {
  User,
  OperatorKYC,
  Trip,
  LiveTelemetry,
  Booking,
  Review,
  ChatMessage,
  SecurityEvent,
  CommissionRule,
  PaymentSplitLedger,
  SupportTicket,
} from '../types';
import { hashPassword } from './security';

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_customer_1',
    name: 'Rahul Sharma',
    email: 'rahul.sharma@example.com',
    phone: '+91 98765 43210',
    authIdentifier: 'rahul.sharma@example.com',
    authMethod: 'email',
    passwordHash: hashPassword('password123'),
    role: 'customer',
    avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
    isVerified: true,
  },
  {
    id: 'usr_operator_1',
    name: 'Vikramaditya Singh',
    email: 'vikram@himalayanyatra.com',
    phone: '+91 98111 22334',
    authIdentifier: '+91 98111 22334',
    authMethod: 'mobile',
    passwordHash: hashPassword('operator123'),
    role: 'operator',
    avatar: 'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=150&q=80',
    isVerified: true,
    operatorCompany: 'Himalayan Yatra Expeditions',
  },
  {
    id: 'usr_operator_2',
    name: 'Ananya Deshmukh',
    email: 'ananya@coastalexpress.in',
    phone: '+91 97222 33445',
    authIdentifier: 'ananya@coastalexpress.in',
    authMethod: 'email',
    passwordHash: hashPassword('coastal123'),
    role: 'operator',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
    isVerified: true,
    operatorCompany: 'Coastal Caravan Tours',
  },
  {
    id: 'usr_agent_1',
    name: 'Priya Mehta (Customer Support)',
    email: 'support@trip2trip.com',
    phone: '+91 1800 888 999',
    authIdentifier: 'support@trip2trip.com',
    authMethod: 'email',
    passwordHash: hashPassword('agent123!'),
    role: 'support_agent',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=150&q=80',
    isVerified: true,
  },
  {
    id: 'usr_admin_1',
    name: 'Trip2Trip Super Admin',
    email: 'admin@trip2trip.com',
    phone: '+91 1800 123 4567',
    authIdentifier: 'admin@trip2trip.com',
    authMethod: 'email',
    passwordHash: hashPassword('adminPass123!'),
    role: 'admin',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    isVerified: true,
    mfaEnabled: true,
  },
];

export const INITIAL_COMMISSION_RULES: CommissionRule[] = [
  {
    id: 'rule_global_1',
    level: 'global',
    commissionPercentage: 10, // Base 10%
    updatedAt: new Date().toISOString(),
    updatedBy: 'Trip2Trip Super Admin',
  },
  {
    id: 'rule_agency_1',
    level: 'agency',
    targetId: 'usr_operator_1',
    targetName: 'Himalayan Yatra Expeditions',
    commissionPercentage: 8, // Special 8% override for high-volume vendor
    updatedAt: new Date().toISOString(),
    updatedBy: 'Trip2Trip Super Admin',
  },
];

export const INITIAL_OPERATOR_KYC: OperatorKYC[] = [
  {
    id: 'kyc_op_1',
    operatorId: 'usr_operator_1',
    companyName: 'Himalayan Yatra Expeditions',
    ownerName: 'Vikramaditya Singh',
    email: 'vikram@himalayanyatra.com',
    phone: '+91 98111 22334',
    aadhaarNumber: '4532 9812 7711',
    panNumber: 'ABCDE1234F',
    gstNumber: '07AAAAA0000A1Z5',
    travelAgencyReg: 'DL-MOT-2024-9981',
    bankAccount: '992100448123',
    ifscCode: 'HDFC0001234',
    upiId: 'himalayanyatra@hdfcbank',
    pennyDropVerified: true,
    pennyDropRecipientName: 'VIKRAMADITYA SINGH',
    address: 'Suite 402, Connaught Place, New Delhi',
    emergencyContact: '+91 98111 22335',
    logoUrl: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=200&q=80',
    status: 'approved',
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'kyc_op_2',
    operatorId: 'usr_operator_2',
    companyName: 'Coastal Caravan Tours',
    ownerName: 'Ananya Deshmukh',
    email: 'ananya@coastalexpress.in',
    phone: '+91 97222 33445',
    aadhaarNumber: '9988 7766 5544',
    panNumber: 'XYZPS9876K',
    gstNumber: '27BBBBB1111B1Z2',
    travelAgencyReg: 'MH-MOT-2024-5511',
    bankAccount: '445511002233',
    ifscCode: 'ICIC0000999',
    upiId: 'coastalcaravan@icici',
    pennyDropVerified: true,
    pennyDropRecipientName: 'ANANYA DESHMUKH',
    address: 'Vashi Sector 17, Navi Mumbai',
    emergencyContact: '+91 97222 33446',
    logoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=200&q=80',
    status: 'approved',
    createdAt: '2026-08-03T14:30:00Z',
  },
];

export const INITIAL_TRIPS: Trip[] = [
  {
    id: 'trip_1',
    name: 'Manali & Solang Valley Volvo Group Expedition',
    category: 'Trekking',
    operatorId: 'usr_operator_1',
    operatorName: 'Himalayan Yatra Expeditions',
    operatorLogo: 'https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=200&q=80',
    operatorRating: 4.9,
    operatorReviewsCount: 142,
    departureCity: 'Delhi',
    destinationCity: 'Manali',
    pickupLocation: { name: 'Kashmiri Gate ISBT, Delhi', lat: 28.6667, lng: 77.2333 },
    dropPoints: [
      { name: 'Chandigarh Tribune Chowk', lat: 30.7077, lng: 76.7972 },
      { name: 'Mandi Bus Stand', lat: 31.7087, lng: 76.932 },
      { name: 'Kullu Bypass Stop', lat: 31.9579, lng: 77.1095 },
      { name: 'Manali Mall Road Terminus', lat: 32.2432, lng: 77.1892 },
    ],
    durationDays: 4,
    durationNights: 3,
    departureDateTime: '2026-08-15T20:00:00Z',
    returnDateTime: '2026-08-19T08:00:00Z',
    pricePerPerson: 7999,
    totalSeats: 30,
    availableSeats: 8,
    bookedSeatNumbers: [1, 2, 5, 6, 9, 10, 11, 14, 15, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
    bookingDeadline: '2026-08-15T12:00:00Z',
    itinerary: [
      {
        dayNumber: 1,
        title: 'Overnight Volvo Journey to Manali',
        activities: ['Board AC Volvo bus at Kashmiri Gate ISBT Delhi at 8:00 PM', 'Overnight highway drive with dinner stop at Murthal'],
        meals: 'Dinner Stop (Self-paid)',
        stayDetails: 'Luxury AC Volvo Bus',
      },
      {
        dayNumber: 2,
        title: 'Arrival in Manali & Hadimba Temple Sightseeing',
        activities: ['Check-in at Hotel Grand Himalayan', 'Visit 400-year-old Hadimba Devi Temple', 'Evening walk on Manali Mall Road'],
        meals: 'Dinner Included',
        stayDetails: 'Hotel Grand Himalayan 4★',
      },
      {
        dayNumber: 3,
        title: 'Solang Valley Adventure & Atal Tunnel Drive',
        activities: ['Excursion to Solang Valley for Paragliding & Zorbing', 'Scenic drive through the iconic Atal Tunnel (9.02 km)', 'Bonfire & DJ Night at hotel'],
        meals: 'Breakfast & Dinner Included',
        stayDetails: 'Hotel Grand Himalayan 4★',
      },
      {
        dayNumber: 4,
        title: 'Jogini Waterfall Trek & Departure',
        activities: ['Morning guided trek to Jogini Waterfalls', 'Visit Vashisht Hot Springs', 'Board return Volvo bus to Delhi'],
        meals: 'Breakfast Included',
        stayDetails: 'Overnight Volvo Journey',
      },
    ],
    inclusions: [
      'Delhi-Manali-Delhi Volvo Bus Transportation',
      '2 Nights Accommodation in 4-Star Hotel',
      'Daily Breakfast & Dinner',
      'Atal Tunnel & Solang Valley Excursions',
      'Certified Tour Guide & 24/7 Group Leader',
    ],
    exclusions: ['Adventure activities fees (Paragliding/Zorbing)', 'Personal expenses & tips', 'Lunch meals'],
    cancellationPolicy: '100% refund 7 days before departure. 50% refund 3 days before. Non-refundable within 24 hrs.',
    requiredDocuments: ['Aadhaar Card or Passport (Original)', 'Valid ID Proof for Hotel Check-in'],
    images: [
      'https://images.unsplash.com/photo-1626621341517-bbf3d9990a23?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1506744038136-46273834b3fb?auto=format&fit=crop&w=800&q=80',
    ],
    tourGuide: {
      name: 'Rohan Verma',
      phone: '+91 98999 11223',
      rating: 4.9,
      languages: ['Hindi', 'English', 'Pahadi'],
      photo: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
    },
    vehicle: {
      type: 'Volvo B11R Multi-Axle AC Sleeper/Seater',
      regNumber: 'HP 01 EXP 8899',
      amenities: ['Reclining Pushback Seats', 'Personal Charging Ports', 'WiFi & Entertainment Screen', 'Live GPS Tracker'],
      driverName: 'Gurdeep Singh',
      driverPhone: '+91 98160 55443',
    },
    hotel: {
      name: 'Hotel Grand Himalayan Resort',
      stars: 4,
      location: 'Left Bank Road, Aleo, Manali',
      images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80'],
    },
    status: 'live',
    difficultyLevel: 'Easy',
    tags: ['Manali', 'Solang Valley', 'Atal Tunnel', 'Volvo Tour', 'Live GPS'],
    routePath: [
      [28.6667, 77.2333],
      [30.7077, 76.7972],
      [31.7087, 76.932],
      [31.9579, 77.1095],
      [32.2432, 77.1892],
    ],
    intermediateCities: ['Delhi', 'Chandigarh', 'Mandi', 'Kullu', 'Manali'],
  },
  {
    id: 'trip_2',
    name: 'Goa Coastal Beach Caravan & Sunset Cruise',
    category: 'Beach Caravan',
    operatorId: 'usr_operator_2',
    operatorName: 'Coastal Caravan Tours',
    operatorLogo: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=200&q=80',
    operatorRating: 4.8,
    operatorReviewsCount: 98,
    departureCity: 'Mumbai',
    destinationCity: 'Goa',
    pickupLocation: { name: 'Bandra Kurla Complex (BKC), Mumbai', lat: 19.0657, lng: 72.8687 },
    dropPoints: [
      { name: 'Pune Chandani Chowk', lat: 18.5074, lng: 73.7806 },
      { name: 'Kolhapur Flyover Stop', lat: 16.705, lng: 74.2433 },
      { name: 'Mapusa Bus Stand Goa', lat: 15.5925, lng: 73.8093 },
      { name: 'Panjim KTC Bus Terminus', lat: 15.4989, lng: 73.8278 },
    ],
    durationDays: 3,
    durationNights: 2,
    departureDateTime: '2026-08-20T21:00:00Z',
    returnDateTime: '2026-08-23T11:00:00Z',
    pricePerPerson: 9499,
    totalSeats: 24,
    availableSeats: 12,
    bookedSeatNumbers: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12],
    bookingDeadline: '2026-08-20T14:00:00Z',
    itinerary: [
      {
        dayNumber: 1,
        title: 'Overnight Sleeper Journey from Mumbai to Goa',
        activities: ['Board Luxury AC Sleeper Bus at BKC Mumbai', 'Overnight highway travel via Kolhapur'],
        meals: 'Dinner Stop (Self-paid)',
        stayDetails: 'Luxury AC Sleeper Coach',
      },
      {
        dayNumber: 2,
        title: 'North Goa Beaches & Mandovi River Sunset Cruise',
        activities: ['Check-in at Calangute Beach Resort', 'Visit Baga & Anjuna Beach', '2-Hour Mandovi River Sunset Cruise with Goan Folk Dance'],
        meals: 'Breakfast & Dinner Included',
        stayDetails: 'Calangute Palms Beach Resort 4★',
      },
      {
        dayNumber: 3,
        title: 'Old Goa Churches & Dudhsagar Waterfalls Tour',
        activities: ['Guided tour of Basilica of Bom Jesus', 'Jeep safari to Dudhsagar Waterfalls', 'Board night sleeper bus back to Mumbai'],
        meals: 'Breakfast Included',
        stayDetails: 'Overnight Sleeper Bus',
      },
    ],
    inclusions: [
      'Mumbai-Goa AC Sleeper Transportation',
      '1 Night Beach Resort Stay',
      'Mandovi River Sunset Cruise Ticket',
      'Dudhsagar Jeep Safari Permits',
    ],
    exclusions: ['Water sports fees', 'Alcoholic beverages'],
    cancellationPolicy: '100% refund 5 days before departure.',
    requiredDocuments: ['Valid Photo ID Proof'],
    images: [
      'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=800&q=80',
      'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80',
    ],
    tourGuide: {
      name: 'Priya Fernandes',
      phone: '+91 98230 44556',
      rating: 4.8,
      languages: ['English', 'Hindi', 'Konkani'],
      photo: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
    },
    vehicle: {
      type: 'Scania Metrolink AC Sleeper Bus',
      regNumber: 'MH 04 CG 5500',
      amenities: ['Individual Reclining Berths', 'Charging Outlets', 'Live GPS Tracking', 'First Aid Kit'],
      driverName: 'Santosh Sawant',
      driverPhone: '+91 97654 33221',
    },
    hotel: {
      name: 'Calangute Palms Beach Resort',
      stars: 4,
      location: 'Calangute Beach Road, North Goa',
      images: ['https://images.unsplash.com/photo-1566073771259-6a8506099945?auto=format&fit=crop&w=800&q=80'],
    },
    status: 'upcoming',
    difficultyLevel: 'Easy',
    tags: ['Goa', 'Beach Caravan', 'Cruise', 'Dudhsagar', 'Live GPS'],
    routePath: [
      [19.0657, 72.8687],
      [18.5074, 73.7806],
      [16.705, 74.2433],
      [15.5925, 73.8093],
      [15.4989, 73.8278],
    ],
    intermediateCities: ['Mumbai', 'Pune', 'Kolhapur', 'Mapusa', 'Panjim'],
  },
];

export const INITIAL_TELEMETRY: Record<string, LiveTelemetry> = {
  trip_1: {
    tripId: 'trip_1',
    currentLat: 31.7087,
    currentLng: 76.932,
    speedKmH: 52,
    headingDeg: 35,
    nextCheckpointName: 'Mandi Bus Stand',
    etaNextCheckpoint: '18 mins (14 km)',
    lastUpdatedIso: new Date().toISOString(),
    emergencyAlertActive: false,
  },
  trip_2: {
    tripId: 'trip_2',
    currentLat: 19.0657,
    currentLng: 72.8687,
    speedKmH: 0,
    headingDeg: 180,
    nextCheckpointName: 'BKC Boarding Terminal',
    etaNextCheckpoint: 'Scheduled Departure 9:00 PM',
    lastUpdatedIso: new Date().toISOString(),
    emergencyAlertActive: false,
  },
};

export const INITIAL_BOOKINGS: Booking[] = [
  {
    id: 'bk_998101',
    tripId: 'trip_1',
    tripName: 'Manali & Solang Valley Volvo Group Expedition',
    operatorName: 'Himalayan Yatra Expeditions',
    customerId: 'usr_customer_1',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98765 43210',
    customerEmail: 'rahul.sharma@example.com',
    selectedSeats: [14, 15],
    totalAmount: 16798,
    paymentMethod: 'UPI',
    paymentStatus: 'paid',
    pickupPoint: 'Kashmiri Gate ISBT, Delhi',
    dropPoint: 'Manali Mall Road Terminus',
    gstInvoiceNumber: 'INV-2026-9981',
    bookingDate: '2026-08-05T12:30:00Z',
    qrCodeData: 'T2T-BK998101-RAHUL-S14S15',
  },
];

export const INITIAL_PAYMENT_SPLIT_LEDGER: PaymentSplitLedger[] = [
  {
    id: 'split_998101',
    bookingId: 'bk_998101',
    tripId: 'trip_1',
    tripName: 'Manali & Solang Valley Volvo Group Expedition',
    operatorId: 'usr_operator_1',
    operatorName: 'Himalayan Yatra Expeditions',
    customerId: 'usr_customer_1',
    customerName: 'Rahul Sharma',
    grossAmount: 16798,
    platformCommissionPercentage: 8, // Agency specific rule
    platformCommissionAmount: 1343.84,
    gstOnCommissionAmount: 241.89, // 18% GST on Commission
    tdsAmount: 167.98, // 1% TDS
    agencyNetSettlementAmount: 15044.29,
    settlementStatus: 'settled',
    settlementSchedule: 'T+1',
    nodalEscrowTransactionId: 'NODAL_TXN_RZP_8899123',
    pennyDropVerified: true,
    createdAt: '2026-08-05T12:30:00Z',
    settledAt: '2026-08-06T10:00:00Z',
  },
];

export const INITIAL_SUPPORT_TICKETS: SupportTicket[] = [
  {
    id: 'tkt_7710',
    bookingId: 'bk_998101',
    tripName: 'Manali & Solang Valley Volvo Group Expedition',
    customerId: 'usr_customer_1',
    customerName: 'Rahul Sharma',
    customerPhone: '+91 98765 43210',
    customerEmail: 'rahul.sharma@example.com',
    category: 'booking_inquiry',
    priority: 'medium',
    status: 'in_progress',
    subject: 'Request regarding luggage space and Mandi pickup stop',
    assignedAgentName: 'Priya Mehta (Customer Support)',
    messages: [
      {
        id: 'msg_1',
        senderId: 'usr_customer_1',
        senderName: 'Rahul Sharma',
        senderRole: 'customer',
        message: 'Hi support team, can I carry 2 extra suitcases on the Manali Volvo bus?',
        timestamp: '2026-08-06T14:00:00Z',
      },
      {
        id: 'msg_2',
        senderId: 'usr_agent_1',
        senderName: 'Priya Mehta (Customer Support)',
        senderRole: 'support_agent',
        message: 'Hello Rahul! Yes, each passenger is allowed 1 main trolley luggage + 1 handbag. Additional luggage is accommodated in the Volvo lower storage boot free of charge.',
        timestamp: '2026-08-06T14:15:00Z',
      },
    ],
    createdAt: '2026-08-06T14:00:00Z',
    updatedAt: '2026-08-06T14:15:00Z',
  },
];

export const INITIAL_REVIEWS: Review[] = [
  {
    id: 'rev_1',
    tripId: 'trip_1',
    operatorId: 'usr_operator_1',
    customerId: 'usr_customer_1',
    customerName: 'Rahul Sharma',
    operatorRating: 5,
    driverRating: 5,
    guideRating: 5,
    comment: 'Exceptional group tour! The live GPS telemetry was super accurate, bus driver was safe, and hotel stay in Manali was top-notch.',
    photos: [],
    createdAt: '2026-08-06T15:00:00Z',
  },
];

export const INITIAL_CHAT: ChatMessage[] = [
  {
    id: 'chat_1',
    tripId: 'trip_1',
    senderId: 'usr_operator_1',
    senderName: 'Vikramaditya Singh',
    senderRole: 'operator',
    text: 'Welcome to the Manali Volvo Group Expedition! Bus HP 01 EXP 8899 will report to Kashmiri Gate ISBT at 7:30 PM.',
    timestamp: '2026-08-15T17:00:00Z',
  },
];

export const INITIAL_SECURITY_LOGS: SecurityEvent[] = [
  {
    id: 'sec_1',
    timestamp: new Date(Date.now() - 3600000).toISOString(),
    eventType: 'LOGIN_SUCCESS',
    identifier: 'rahul.sharma@example.com',
    details: 'User authenticated via Email + Password',
    ipAddress: '122.160.10.4',
  },
  {
    id: 'sec_2',
    timestamp: new Date(Date.now() - 7200000).toISOString(),
    eventType: 'ADMIN_MFA_SUCCESS',
    identifier: 'admin@trip2trip.com',
    details: 'Super Admin authenticated with mandatory 2FA MFA OTP',
    ipAddress: '49.207.18.99',
  },
];
